version: '3'

services:
  db:
    image: postgres 
    environment:
            POSTGRES_DB: wku_sims
            POSTGRES_USER: wku_sims
            POSTGRES_PASSWORD: wku_sims
  web:
    build: .
#   command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/wku_sims
    ports:
      - "8000:8000"
    depends_on:
      - db
