# Generated by Django 2.2.12 on 2020-05-07 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('header', 'Header'), ('text', 'Text'), ('blank', 'Blank')], max_length=100, null='True')),
                ('inches_blank', models.FloatField(null='True')),
                ('text', models.CharField(max_length=10000, null='True')),
                ('next_element', models.OneToOneField(null='True', on_delete=django.db.models.deletion.SET_NULL, to='lab_repo.Element')),
            ],
        ),
        migrations.CreateModel(
            name='LabTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000, null='True')),
                ('template', models.FileField(upload_to='lab_repo_template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('draft', models.FileField(upload_to='lab_repo_drafts')),
                ('current', models.BooleanField(default='False')),
                ('next_element', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, to='lab_repo.Element')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
