# Generated by Django 3.0.5 on 2020-05-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_repo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='lines_blank',
        ),
        migrations.RemoveField(
            model_name='labtemplate',
            name='next_element',
        ),
        migrations.AddField(
            model_name='element',
            name='inches_blank',
            field=models.FloatField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='labtemplate',
            name='description',
            field=models.CharField(max_length=10000, null='True'),
            preserve_default='True',
        ),
    ]
